CREATE TABLE [dbo].[PolizaHogar] (
    [id]                                 INT           IDENTITY (1, 1) NOT NULL,
    [tipoVivienda]                       NVARCHAR (50) NOT NULL,
    [zonaVivienda]                       NVARCHAR (50) NOT NULL,
    [anhoConstruccion]                   NVARCHAR (4)  NOT NULL,
    [metrosConstruidos]                  NVARCHAR (10) NOT NULL,
    [metrosTotales]                      NVARCHAR (10) NOT NULL,
    [valorVivienda]                      NVARCHAR (50) NOT NULL,
    [valorContenido]                     NVARCHAR (50) NOT NULL,
    [habitaciones]                       NVARCHAR (10) NOT NULL,
    [mascota]                            NVARCHAR (5)  NOT NULL,
    [piscina]                            NVARCHAR (5)  NOT NULL,
    [garaje]                             NVARCHAR (5)  NOT NULL,
    [personalSeguridad]                  NVARCHAR (5)  NOT NULL,
    [camaras]                            NVARCHAR (5)  NOT NULL,
    [cajaFuerte]                         NVARCHAR (5)  NOT NULL,
    [verja]                              NVARCHAR (5)  NOT NULL,
    [alarma]                             NVARCHAR (5)  NOT NULL,
    [tipoMaterial]                       NVARCHAR (50) NOT NULL,
    [usoVivienda]                        NVARCHAR (50) NOT NULL,
    [roboEnCasa]                         NVARCHAR (5)  NOT NULL,
    [incendio]                           NVARCHAR (5)  NOT NULL,
    [fenomenosAtmosfericos]              NVARCHAR (5)  NOT NULL,
    [responsabilidadDaniosEstructurales] NVARCHAR (5)  NOT NULL,
    [roturaCristales]                    NVARCHAR (5)  NOT NULL,
    [aguaElectricidad]                   NVARCHAR (5)  NOT NULL,
    [inhabitabilidad]                    NVARCHAR (5)  NOT NULL,
    [defensaJuridica]                    NVARCHAR (5)  NOT NULL,
    [roturaTuberias]                     NVARCHAR (5)  NOT NULL,
    [derrumbe]                           NVARCHAR (5)  NOT NULL,
    [asistenciaInformacion]              NVARCHAR (5)  NOT NULL,
    [asistenciaViaje]                    NVARCHAR (5)  NOT NULL,
    [actosVandalicos]                    NVARCHAR (5)  NOT NULL,
    [promociones]                        NVARCHAR (5)  NOT NULL,
    [reparacion24Horas]                  NVARCHAR (5)  NOT NULL,
    [vehiculoEnGaraje]                   NVARCHAR (5)  NOT NULL,
    [juridicaAvanzada]                   NVARCHAR (5)  NOT NULL,
    [dni]                                NVARCHAR (20) NOT NULL,
    [precio]                             NVARCHAR (50) NOT NULL,
    PRIMARY KEY CLUSTERED ([id] ASC)
);

