CREATE TABLE [dbo].[PolizaVida] (
    [Id]                         INT          IDENTITY (1, 1) NOT NULL,
    [Edad]                       VARCHAR (10) NOT NULL,
    [Sexo]                       VARCHAR (10) NOT NULL,
    [OcupacionId]                  INT		  NOT NULL,
    [Peso]                       VARCHAR (20) NOT NULL,
    [Altura]                     VARCHAR (20) NOT NULL,
    [DietaId]                    INT		  NOT NULL,
    [ActividadId]                INT		  NOT NULL,
    [ConsumeAlcohol]             VARCHAR (5)  NOT NULL,
    [ConsumeTabaco]              VARCHAR (5)  NOT NULL,
    [ConsumeDrogas]              VARCHAR (5)  NOT NULL,
    [Hematologicas]              VARCHAR (5)  NOT NULL,
    [Gastrointestinales]         VARCHAR (5)  NOT NULL,
    [Endocrinas]                 VARCHAR (5)  NOT NULL,
    [Infecciosas]                VARCHAR (5)  NOT NULL,
    [Autoinmunes]                VARCHAR (5)  NOT NULL,
    [Neurologicas]               VARCHAR (5)  NOT NULL,
    [Renales]                    VARCHAR (5)  NOT NULL,
    [Hepaticas]                  VARCHAR (5)  NOT NULL,
    [Diabetes]                   VARCHAR (5)  NOT NULL,
    [Cancer]                     VARCHAR (5)  NOT NULL,
    [Respiratorias]              VARCHAR (5)  NOT NULL,
    [Cardiacas]                  VARCHAR (5)  NOT NULL,
    [TieneTerminacionAnticipada] VARCHAR (5)  NOT NULL,
    [TieneIncapacidadTemporal]   VARCHAR (5)  NOT NULL,
    [TieneAccidentes]            VARCHAR (5)  NOT NULL,
    [CapitalAsegurado]           VARCHAR (20) NOT NULL,
    [Precio]                     VARCHAR (20) NOT NULL,
    [Dni]                        VARCHAR (20) NOT NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC),
    FOREIGN KEY ([DietaId]) REFERENCES [dbo].[Dieta] ([Id]),
    FOREIGN KEY ([ActividadId]) REFERENCES [dbo].[Actividad] ([Id]),
    FOREIGN KEY ([Ocupacion]) REFERENCES [dbo].[Trabajo] ([ID])
);
