INSERT INTO Trabajo (Nombre, Descripcion)
VALUES 
('Trabajos en Altura', 'Trabajadores de construcción, pintores de edificios, reparadores de líneas eléctricas, etc.'),
('Trabajos en Espacios Confinados', 'Mineros, operadores de alcantarillas, técnicos de mantenimiento en espacios reducidos, etc.'),
('Trabajos Marítimos', 'Pescadores, marineros, trabajadores en plataformas petroleras, etc.'),
('Trabajos en Altamar', 'Navegantes, personal en barcos de crucero, tripulación de buques de carga, etc.'),
('Trabajos con Exposición a Productos Químicos', 'Trabajadores de plantas químicas, empleados de limpieza industrial, técnicos de laboratorio, etc.'),
('Trabajos de Bomberos y Rescatistas', 'Bomberos, personal de rescate en montaña, rescatistas de emergencia, etc.'),
('Trabajos de Seguridad y Vigilancia', 'Guardias de seguridad, agentes de seguridad personal, escoltas, etc.'),
('Trabajos de Pilotos y Controladores Aéreos', 'Pilotos comerciales, pilotos de helicópteros, controladores de tráfico aéreo, etc.'),
('Trabajos en Demoliciones y Explosivos', 'Trabajadores de demolición, expertos en desactivación de explosivos, etc.'),
('Trabajos de Transporte de Carga Pesada', 'Conductores de camiones de carga, operadores de maquinaria pesada, etc.'),
('Trabajos en Zonas de Conflicto o Peligrosas', 'Personal militar, contratistas de defensa, periodistas en zonas de guerra, etc.'),
('Trabajos en Instalaciones Nucleares', 'Ingenieros nucleares, técnicos de mantenimiento en plantas nucleares, etc.'),
('Trabajos en Agricultura y Ganadería de Alta Intensidad', 'Trabajadores agrícolas expuestos a pesticidas, ganaderos en áreas de alto riesgo, etc.'),
('Trabajos en Fábricas y Plantas Industriales', 'Operadores de maquinaria pesada, trabajadores en líneas de producción, etc.'),
('Trabajos de Oficina', 'Empleados administrativos, analistas, etc.'),
('Trabajos en Servicios de Alimentación', 'Camareros, cocineros, personal de servicio en restaurantes, etc.'),
('Trabajos de Ventas y Atención al Cliente', 'Vendedores, representantes comerciales, atención al cliente, etc.'),
('Trabajos de Educación', 'Maestros, profesores, personal educativo, etc.'),
('Trabajos de Tecnología de la Información', 'Desarrolladores de software, ingenieros de sistemas, personal de soporte técnico, etc.'),
('Trabajos Creativos', 'Diseñadores gráficos, artistas, escritores, etc.'),
('Trabajos en Salud y Cuidado Personal', 'Médicos, enfermeras, fisioterapeutas, esteticistas, etc.'),
('Trabajos del Sector Servicios', 'Meseros, camareras, recepcionistas de hoteles, etc.'),
('Trabajos del Sector del Entretenimiento', 'Actores, músicos, técnicos de iluminación, etc.'),
('Trabajos del Sector del Transporte', 'Conductores de taxis, conductores de autobuses, pilotos de tren, etc.'),
('Trabajos del Sector Financiero', 'Banqueros, contadores, analistas financieros, etc.'),
('Trabajos del Sector de la Construcción', 'Albañiles, carpinteros, electricistas, etc.'),
('Trabajos del Sector Educativo', 'Profesores universitarios, tutores privados, educadores infantiles, etc.'),
('Trabajos del Sector de la Salud Mental', 'Psicólogos, terapeutas, consejeros, etc.'),
('Trabajos del Sector Agrícola', 'Agricultores, cosechadores, trabajadores en viveros, etc.'),
('Trabajos del Sector del Transporte de Pasajeros', 'Conductores de transporte público, pilotos de avión, tripulación de vuelo, etc.'),
('Trabajos del Sector del Turismo', 'Guías turísticos, personal de parques temáticos, etc.');